Always merge repo manifest with module manifest and make it available to all jfdi iac modules for deployment

diff --git a/.github/workflows/store-manifest.yml b/.github/workflows/store-manifest.yml
--- a/.github/workflows/store-manifest.yml
+++ b/.github/workflows/store-manifest.yml
@@ -1,22 +1,40 @@
 name: Store Manifest
 on:
   workflow_call:
-    outputs:
-      manifest:
-        value: ${{ jobs.Store-Manifest.outputs.manifest }}
 
 jobs:
   Store-Manifest:
     runs-on: ubuntu-latest
-    outputs:
-      manifest: ${{ steps.save-manifest.outputs.artifact-id != null && 'manifest' || null }}
     steps:
       - name: Git-Clone
         uses: actions/checkout@v4
+        with:
+          path: repo
+      - name: Clone-JFDI-IAC
+        uses: actions/checkout@v4
+        with:
+          repository: jfdi-dev/iac
+          path: iac
+      # Fail if requested module cannot be found
+      - name: Check-JFDI-Module-Exists
+        if: ${{ hashFiles(format('iac/modules/root/{0}', inputs.module)) == '' }}
+        run:
+          echo "::error title=JFDI Module Not Found::The specified module `${{ inputs.module }}` could not be found in the `jfdi-dev/iac` repository (`modules/root/` directory)."
+          exit 1
+      # Merge will fail if one of the files does not exist, so create empty manifests if necessary
+      - name: Ensure-Manifests-Exist
+        run: |
+          touch ${{ format('iac/modules/root/{0}', inputs.module) }}
+          touch 'repo/manifest.yml'
+        shell: bash
+      - name: Merge-Manifests
+        if: ${{ hashFiles('repo/manifest.yml') != '' }}
+        run: |
+          yq '. *+ load("${{ format('iac/modules/root/{0}', inputs.module) }}")' repo/manifest.yml > manifest.yml
+        shell: bash
       - name: Save-Manifest
         id: save-manifest
         uses: actions/upload-artifact@v4
-        if: ${{ hashFiles('manifest.yml') != '' }}
         with:
           name: manifest
           path: manifest.yml
